# Question-1:

In [6]:
import numpy as np
array = np.arange(start = 2, stop = 50, step = 3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question-2:

In [27]:
import numpy as np
firstList = input().split()
secondList = input().split()
listToarray1 = np.array(firstList)
listToarray2 = np.array(secondList)
sortedList = firstList + secondList
k=np.sort(sortedList)
print(k)

98 27 1 56 35
12 42 63 71 82
['1' '12' '27' '35' '42' '56' '63' '71' '82' '98']


# Question-3:

In [23]:
import numpy as np
Dimension = np.arange(9).reshape((3,3))

print("Value:",Dimension)
print("Dimension:",Dimension.ndim)
print("Size:",Dimension.size)

Value: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Dimension: 2
Size: 9


# Question-4:

In [50]:
import numpy as np
arrayValue = np.array([4,1,2,6,8,9])
converted2DArray = np.reshape(arrayValue,(-1,3))
print(converted2DArray)

[[4 1 2]
 [6 8 9]]


# Question-5:

In [60]:
array1 = np.array([[1,2,3]])
array2 = np.array([[4,5,6]])
squaredArray1 = np.square(array1)
squaredArray2 = np.square(array2)
verticalStack = np.vstack((squaredArray1,squaredArray2))
horizontalStack = np.hstack((squaredArray1,squaredArray2))
print("Vertical:",verticalStack)
print("Horizontal:",horizontalStack)

Vertical: [[ 1  4  9]
 [16 25 36]]
Horizontal: [[ 1  4  9 16 25 36]]


# Question-6:

In [66]:
items = [2,2,6,6,7,3,4,2,3,0,20,1,9,7,8,6]
uniqueItems = set(items)
print(uniqueItems)
print("Count:",len(uniqueItems))

{0, 1, 2, 3, 4, 6, 7, 8, 9, 20}
Count: 10
